EvenementsTXT = [
  {
  	_id: "4ZvNZ8tAFur38mZfT",
    eventId: "EV1",
    intitule : {fr:"Erreur de la banque en votre faveur.", en:"Bank Error in your favor"},
    description : {fr:"Suite à une erreur humaine, la banque effectue un geste commercial en votre faveur.", en:""},
    tip: {fr:"", en:""},
    illustration: "§Y3.png",
    isLancement : false,
    deltaEur : 5000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "4ZvNZ8tAFur38mZfU",
    eventId: "EV2",
    intitule : {fr:"Erreur de la banque en votre faveur.", en:"Bank Error in your favor"},
    description : {fr:"Suite à une erreur humaine, la banque effectue un geste commercial en votre faveur.", en:""},
    tip: {fr:"", en:""},
    illustration: "§Y3.png",
    isLancement : false,
    deltaEur : 7500,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "4ZvNZ8tAFur38mZfV",
    eventId: "EV3",
    intitule : {fr:"Erreur de la banque en votre faveur.", en:"Bank Error in your favor"},
    description : {fr:"", en:""},
    tip: {fr:"", en:""},
    illustration: "§Y3.png",
    isLancement : false,
    deltaEur : 10000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "4ZvNZ8tAFur38mZfW",
    eventId: "EV4",
    intitule : {fr:"Erreur de la banque en votre faveur.", en:"Bank Error in your favor"},
    description : {fr:"", en:""},
    tip: {fr:"", en:""},
    illustration: "§Y3.png",
    isLancement : false,
    deltaEur : 2000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "4ZvNZ8tAFur38mZfX",
    eventId: "EV5",
    intitule : {fr:"Erreur de la banque en votre faveur.", en:"Bank Error in your favor"},
    description : {fr:"", en:""},
    tip: {fr:"", en:""},
    illustration: "§Y3.png",
    isLancement : false,
    deltaEur : 6000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "4d9auFybk9diNuAP4",
    eventId: "EV6",
    intitule : {fr:"Innovation rentabilisée.", en:"Innovation made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer des capteurs rendant les automobiles plus performantes.", en:"Congratulations, your mission has created sensors making them more efficient automobiles. Add 20M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y2.png",
    isLancement : false,
    deltaEur : 20000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "4d9auFybk9diNuAP5",
    eventId: "EV7",
    intitule : {fr:"Innovation rentabilisée.", en:"Innovation made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer des capteurs rendant les automobiles plus performantes.", en:"Congratulations, your mission has created sensors making them more efficient automobiles. Add 20M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y2.png",
    isLancement : false,
    deltaEur : 25000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "4d9auFybk9diNuAP6",
    eventId: "EV8",
    intitule : {fr:"Innovation rentabilisée.", en:"Innovation made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer des capteurs rendant les automobiles plus performantes.", en:"Congratulations, your mission has created sensors making them more efficient automobiles. Add 20M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y2.png",
    isLancement : false,
    deltaEur : 27500000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "4d9auFybk9diNuAP7",
    eventId: "EV9",
    intitule : {fr:"Innovation rentabilisée.", en:"Innovation made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer des capteurs rendant les automobiles plus performantes.", en:"Congratulations, your mission has created sensors making them more efficient automobiles. Add 20M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y2.png",
    isLancement : false,
    deltaEur : 30000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "ycpDqAMXsgL76fEzh",
    eventId: "EV10",
    intitule : {fr:"Logiciel rentabilisé.", en:"Software made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer un logiciel de navigation plus performant.", en:"Congratulations, your mission has created a more efficient browser. Add 30M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y2.png",
    isLancement : false,
    deltaEur : 30000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "ycpDqAMXsgL76fEzi",
    eventId: "EV11",
    intitule : {fr:"Logiciel rentabilisé.", en:"Software made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer un logiciel de navigation plus performant.", en:"Congratulations, your mission has created a more efficient browser. Add 30M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y2.png",
    isLancement : false,
    deltaEur : 32500000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "ycpDqAMXsgL76fEzj",
    eventId: "EV12",
    intitule : {fr:"Logiciel rentabilisé.", en:"Software made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer un logiciel de navigation plus performant.", en:"Congratulations, your mission has created a more efficient browser. Add 30M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y2.png",
    isLancement : false,
    deltaEur : 35000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "EaieufBJapEjmmbFm",
    eventId: "EV13",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 20 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y4.png",
    isLancement : false,
    deltaEur : 5000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "EaieufBJapEjmmbFn",
    eventId: "EV14",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 20 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y4.png",
    isLancement : false,
    deltaEur : 6000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "EaieufBJapEjmmbFo",
    eventId: "EV15",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 20 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y4.png",
    isLancement : false,
    deltaEur : 1000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "EaieufBJapEjmmbFp",
    eventId: "EV16",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 20 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y4.png",
    isLancement : false,
    deltaEur : 2000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "EaieufBJapEjmmbFq",
    eventId: "EV17",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 20 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y4.png",
    isLancement : false,
    deltaEur : 1500000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "CCXuBnRz5ycKepJW4",
    eventId: "EV18",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 2 000 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "§Y4.png",
    isLancement : false,
    deltaEur : 500000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "fNgzJPBKWpEkhpqdf",
    eventId: "EV19",
    intitule : {fr:"Panne", en:"Breakdown"},
    description : {fr:"Hélas, un problème se produit durant la mission (éruption solaire, micrométéorite) et un composant est perdu..", en:"Alas, a problem occurs during the mission ( solar flare , micrometeorite ) and a component is lost."},
    tip: {fr:"", en:""},
    illustration: "§Y15.png",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: ["instrument"],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "JWLYEijLypahZggvN",
    eventId: "EV20",
    intitule : {fr:"Panne", en:"Breakdown"},
    description : {fr:"Hélas, un problème se produit durant la mission (éruption solaire, micrométéorite) et un composant est perdu..", en:"Alas, a problem occurs during the mission ( solar flare , micrometeorite ) and a component is lost."},
    tip: {fr:"", en:""},
    illustration: "§Y15.png",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: ["instrument"],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "VNcEcArO2KG3rMB4s",
    eventId: "EV21",
    intitule : {fr:"Heureux évènement", en:"Happy event"},
    description : {fr:"Vous avez eu la chance de pouvoir observer une météorite inattendue durant votre mission.", en:"You had the chance to observe an unexpected meteorite during your mission."},
    tip: {fr:"+1 point scientifique", en:"+1 scientific point"},
    illustration: "§Y9.png",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 1,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "VNcEcArO2KG3rMB4t",
    eventId: "EV22",
    intitule : {fr:"Heureux évènement", en:"Happy event"},
    description : {fr:"Vous avez eu la chance de pouvoir observer une météorite inattendue durant votre mission.", en:"You had the chance to observe an unexpected meteorite during your mission."},
    tip: {fr:"+1 point scientifique", en:"+1 scientific point"},
    illustration: "§Y9.png",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 1,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    _id: "Ism43lAD4v1dC0n4r",
    eventId: "EV23",
    intitule : {fr:"Tempête solaire", en:"Solar Storm"},
    description : {fr:"Une tempête solaire a perturbé momentanément vos instruments.", en:"A solar storm disrupted momentarily your instruments."},
    tip: {fr:"-1 point scientifique", en:"-1 scientific point"},
    illustration: "§Y17.png",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : -1,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    _id: "Ism43lAD4v1dC0n4s",
    eventId: "EV24",
    intitule : {fr:"Tempête solaire", en:"Solar Storm"},
    description : {fr:"Une tempête solaire a perturbé momentanément vos instruments.", en:"A solar storm disrupted momentarily your instruments."},
    tip: {fr:"-1 point scientifique", en:"-1 scientific point"},
    illustration: "§Y17.png",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : -1,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  }
];