EvenementsTXT = [
  {
  	eventId: "EV1",
    intitule : {fr:"Erreur de la banque en votre faveur.", en:"Bank Error in your favor"},
    description : {fr:"", en:""},
    tip: {fr:"", en:""},
    illustration: "",
    isLancement : false,
    deltaEur : 5000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    eventId: "EV2",
    intitule : {fr:"Innovation rentabilisée.", en:"Innovation made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer des capteurs rendant les automobiles plus performantes. Ajoutez 20M€ à votre budget.", en:"Congratulations, your mission has created sensors making them more efficient automobiles. Add 20M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "",
    isLancement : false,
    deltaEur : 20000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    eventId: "EV3",
    intitule : {fr:"Logiciel rentabilisé.", en:"Software made profitable"},
    description : {fr:"Félicitations, votre mission a permis de créer un logiciel de navigation plus performant. Ajoutez 30M€ à votre budget.", en:"Congratulations, your mission has created a more efficient browser. Add 30M€ to your budget."},
    tip: {fr:"", en:""},
    illustration: "",
    isLancement : false,
    deltaEur : 30000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    eventId: "EV4",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget de 20 000€. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 20 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "",
    isLancement : false,
    deltaEur : 20000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    eventId: "EV5",
    intitule : {fr:"Taxe européenne", en:"European tax"},
    description : {fr:"Hélas, les problèmes budgétaires européens conduisent à une réduction de votre budget de 2 000 000€. Revoyez la conception de votre mission pour rester dans les limites de votre budget.", en:"Alas , European fiscal problems lead to a reduction in your budget of 2 000 000 € . Review the design of your mission to stay within your budget."},
    tip: {fr:"", en:""},
    illustration: "",
    isLancement : false,
    deltaEur : 2000000,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: [],
    active : true,
    cubesat: true,
    copyright: ""
  },
  {
    eventId: "EV6",
    intitule : {fr:"Panne", en:"Breakdown"},
    description : {fr:"Hélas, un problème se produit durant la mission (éruption solaire, micrométéorite) et un composant est perdu..", en:"Alas, a problem occurs during the mission ( solar flare , micrometeorite ) and a component is lost."},
    tip: {fr:"", en:""},
    illustration: "",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: ["instrument"],
    active : true,
    cubesat: false,
    copyright: ""
  },
  {
    eventId: "EV7",
    intitule : {fr:"Panne", en:"Breakdown"},
    description : {fr:"Hélas, un problème se produit durant la mission (éruption solaire, micrométéorite) et un composant est perdu..", en:"Alas, a problem occurs during the mission ( solar flare , micrometeorite ) and a component is lost."},
    tip: {fr:"", en:""},
    illustration: "",
    isLancement : true,
    deltaEur : 0,
    deltaNrg : 0,
    deltaPds : 0,
    deltaVol : 0,
    deltaSci : 0,
    targetCarteIds: [],
    targetCarteTags: ["instrument"],
    active : true,
    cubesat: true,
    copyright: ""
  }
];