ListActions = [
	"CARTE-ACTIVE",
	"CARTE-DEL", 
	"CARTE-NEW", 
	"CARTE-UPD",
	"DECK-ADD",
	"DECK-REM",
	"EVENT-ACTIVE",
	"EVENT-DEL", 
	"EVENT-NEW", 
	"EVENT-UPD",
	"PARTIE-DEL",
	"PEER-CALL",
	"PEER-NOCALL-BUDGET",
	"PEER-NOMORECALL",
	"PEER-STILLCALL",
	"PEER-TOOLATE",
	"USER-CALL",
	"USER-MSG",
	"USER-NOCALL-BUDGET"
];
ListTokens = [
];